print("!:Si alguno de los numeros va acompañado de un . se considera flotante")
print("EXPONENCIACION")
print(2 ** 3) 
print(2 ** 3.) 
print(2. ** 3)  
print(2. ** 3.) 
print("MULTIPLICACION")
print(2 * 3)
print(2 * 3.)
print(2. * 3)
print(2. * 3.)
print("DIVISION")
print(6 / 3)
print(6 / 3.)
print(6. / 3)
print(6. / 3.)
